<div id="logos">
  <div class="helper">
    <a href="http://workforcecompliancesafety.ca" target="_blank"><img src="img/logo_cor.jpg" alt=""></a>
    <a href="http://albertaconstruction.net" target="_blank"><img src="img/logo_aca.jpg" alt=""></a>
    <a href="http://www.bbb.org/calgary/" target="_blank"><img src="img/logo_bbb.gif" alt=""></a>
    <a href="http://www.meritalberta.com" target="_blank"><img src="img/logo_merit.jpg" alt=""></a>
    <a href="http://www.isnetworld.com" target="_blank"><img src="img/logo_isn.png" alt=""></a>
  </div>
</div>


<p>Copyright 2014 &copy; Cemrock Concrete &amp; Construction<br>
    All Rights Reserved <br><br>
    <a href="privacy.html" class="gallery cboxElement" id="privacy_link">Privacy Policy</a>
</p>

<br><br>
<p style="text-align: center;">
  <a href="http://validator.w3.org/check?uri=referer">
    <img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Strict" height="20" width="54">
  </a>
  <a href="http://jigsaw.w3.org/css-validator/check/referer">
    <img style="border:0;width:54px;height:20px" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!">
  </a>
</p>
