<div id="logos">
  <div class="helper">
    <a href="http://workforcecompliancesafety.ca" target="_blank"><img src="img/logo_cor.jpg" alt=""></a>
    <a href="http://albertaconstruction.net" target="_blank"><img src="img/logo_aca.jpg" alt=""></a>
    <a href="http://www.bbb.org/calgary/" target="_blank"><img src="img/logo_bbb.gif" alt=""></a>
    <a href="http://www.meritalberta.com" target="_blank"><img src="img/logo_merit.jpg" alt=""></a>
    <a href="http://www.isnetworld.com" target="_blank"><img src="img/logo_isn.png" alt=""></a>
  </div>
</div>


<p>Copyright 2014 &copy; Cemrock Concrete &amp; Construction<br>
    All Rights Reserved <br><br>
    <a href="privacy.html" class="gallery cboxElement" id="privacy_link">Privacy Policy</a>
</p>
