<!-- <head> content, to be included in every page -->
<!-- contains font link, css link,                -->
<!-- author + description, favicon, colorbox link -->
<!-- and init                                     -->

<meta charset="utf-8"/>
<!-- font -->
<link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
<title>Cemrock - Concrete & Construction</title>
<meta name="description" content="Cemrock - Concrete & Construction">
<meta name="author" content="Daniel" >
<!-- styles -->
<link rel="stylesheet" href="css/style.css?v=1.0">
<!-- icon -->
<link rel="icon" href="favicon.ico" type="image/x-icon">
<!-- colorBox -->
<script src="./colorbox/jquery-1.11.0.min.js"></script>
<link href="./colorbox/colorbox.css" rel="stylesheet" />
<script src="./colorbox/jquery.colorbox-min.js"></script>
<script>
  $(document).ready(function(){
    $(".gallery").colorbox({transition:"elastic", maxWidth:"90%", maxHeight:"90%", scalePhotos:true});
  });
</script>
